configuration-as-code: {
  }
credentials:
  folder: {
    }
  providerImpl: {
    }
  system:
    domainCredentials:
    - domain: {
        }
  user: {
    }
jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.diagnostics.ControllerExecutorsNoAgents"
  - "jenkins.security.csp.impl.CspRecommendation"
  labelAtoms:
  - name: "built-in"
  log: {
    }
  markupFormatter: "plainText"
  mode: NORMAL
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: ${JENKINS_ADMIN_ID}
        password: ${JENKINS_ADMIN_PASSWORD}
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  consoleUrlProvider: {
    }
  pipelineGraphView:
    showGraphOnBuildPage: false
    showGraphOnJobPage: false
    showStageDurations: false
    showStageNames: false
  prism:
    theme: PRISM
  themeManager:
    disableUserThemes: false
    theme: "noOp"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  apiTokenProperty: {
    }
  contentSecurityPolicy:
    enforce: false
  cps:
    hideSandbox: false
  crumb: {
    }
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  prism:
    protectSourceCodeByPermission: false
  queueItemAuthenticator: {
    }
  scriptApproval:
    forceSandbox: false
  updateSiteWarningsConfiguration: {
    }
unclassified:
  administrativeMonitorsConfiguration: {
    }
  artifactManager: {
    }
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  casCGlobalConfig: {
    }
  computerRetentionCheckInterval: {
    }
  defaultDisplayUrlProvider: {
    }
  defaultFolderConfiguration: {
    }
  defaultView: {
    }
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    mailAccount: {
      }
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    throttlingEnabled: false
    watchingEnabled: false
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  envVarsFilter: {
    }
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  globalDefaultFlowDurabilityLevel: {
    }
  globalLibraries: {
    }
  globalTimeOutConfiguration:
    operations:
    - "abortOperation"
    overwriteable: false
  globalUntrustedLibraries: {
    }
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    injectCcudExtension: false
    injectMavenExtension: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://localhost:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  metricsAccessKey: {
    }
  myView: {
    }
  nodeProperties: {
    }
  pipeline-model-docker: {
    }
  plugin: {
    }
  pollSCM:
    pollingThreadCount: 10
  projectNamingStrategy: {
    }
  proxyConfigurationManager: {
    }
  quietPeriod: {
    }
  resourceRoot: {
    }
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  scmRetryCount: {
    }
  shell: {
    }
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  usageStatistics: {
    }
  viewsTabBar: {
    }
tool:
  dockerTool:
    installations:
    - name: "docker tramitrack"
      properties:
      - installSource:
          installers:
          - docker:
              version: "latest"
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
jobs:
  - script: >
      pipelineJob('tramitrack-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/DiegoBranco/TramiTrack.git')
                }
                branch('main')
              }
            }
            scriptPath('tramitrack/Jenkinsfile')
          }
        }
      }
