/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin-home': RouteRecordInfo<'/admin-home', '/admin-home', Record<never, never>, Record<never, never>>,
    '/admin-info-tramite': RouteRecordInfo<'/admin-info-tramite', '/admin-info-tramite', Record<never, never>, Record<never, never>>,
    '/admin-profile': RouteRecordInfo<'/admin-profile', '/admin-profile', Record<never, never>, Record<never, never>>,
    '/admin-tipo-tramite': RouteRecordInfo<'/admin-tipo-tramite', '/admin-tipo-tramite', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/info-tramite': RouteRecordInfo<'/info-tramite', '/info-tramite', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/solicitar-constancia': RouteRecordInfo<'/solicitar-constancia', '/solicitar-constancia', Record<never, never>, Record<never, never>>,
    '/soporte': RouteRecordInfo<'/soporte', '/soporte', Record<never, never>, Record<never, never>>,
    '/tipo-tramite': RouteRecordInfo<'/tipo-tramite', '/tipo-tramite', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin-home.vue': {
      routes: '/admin-home'
      views: never
    }
    'src/pages/admin-info-tramite.vue': {
      routes: '/admin-info-tramite'
      views: never
    }
    'src/pages/admin-profile.vue': {
      routes: '/admin-profile'
      views: never
    }
    'src/pages/admin-tipo-tramite.vue': {
      routes: '/admin-tipo-tramite'
      views: never
    }
    'src/pages/home.vue': {
      routes: '/home'
      views: never
    }
    'src/pages/info-tramite.vue': {
      routes: '/info-tramite'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/profile.vue': {
      routes: '/profile'
      views: never
    }
    'src/pages/solicitar-constancia.vue': {
      routes: '/solicitar-constancia'
      views: never
    }
    'src/pages/soporte.vue': {
      routes: '/soporte'
      views: never
    }
    'src/pages/tipo-tramite.vue': {
      routes: '/tipo-tramite'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
