FROM postman/newman:alpine

WORKDIR /etc/newman

# 1. Instalamos pnpm v8
RUN npm install -g pnpm@8

# 2. Configuramos las carpetas para que pnpm no de error de "Global Bin"
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"

# 3. Instalamos el reportero (ahora sí encontrará la ruta)
RUN pnpm add -g newman-reporter-htmlextra

ENTRYPOINT ["newman"]