FROM postman/newman:alpine

WORKDIR /etc/newman

# Instalamos una versión de pnpm compatible con Node 16 (la versión 8)
RUN npm install -g pnpm@8

# Instalamos el reportero
RUN pnpm add -g newman-reporter-htmlextra

ENTRYPOINT ["newman"]